# -*- coding: utf-8 -*-
"""fuel_effeciency_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yw4u3M7Ag97o-XYggf1lyRDYEtsk6yWo
"""

import streamlit as st
import numpy as np
import joblib

st.title("🚗 Vehicle Fuel Efficiency Prediction (MPG)")
st.write("This app loads pre-trained models from `.pkl` files and predicts fuel efficiency interactively.")

# -------------------------------
# Load Models
# -------------------------------
@st.cache_resource
def load_models():
    lin_model = joblib.load("linear_model.pkl")
    rf_model = joblib.load("random_forest_model.pkl")
    gb_model = joblib.load("gradient_boosting_model.pkl")
    return lin_model, rf_model, gb_model

lin_model, rf_model, gb_model = load_models()

# -------------------------------
# User Input for Prediction
# -------------------------------
st.subheader("🔮 Predict MPG for a Vehicle")

cylinders = st.number_input("Cylinders", min_value=3, max_value=12, value=4)
displacement = st.number_input("Displacement", min_value=50, max_value=500, value=150)
horsepower = st.number_input("Horsepower", min_value=40, max_value=300, value=100)
weight = st.number_input("Weight", min_value=1500, max_value=6000, value=2500)
acceleration = st.number_input("Acceleration", min_value=8.0, max_value=30.0, value=15.0)
model_year = st.number_input("Model Year", min_value=70, max_value=82, value=76)
origin = st.selectbox("Origin", [1, 2, 3])

input_data = np.array([[cylinders, displacement, horsepower, weight, acceleration, model_year, origin]])

model_choice = st.selectbox("Choose Model", ["Linear Regression", "Random Forest", "Gradient Boosting"])

if st.button("Predict MPG"):
    if model_choice == "Linear Regression":
        prediction = lin_model.predict(input_data)[0]
    elif model_choice == "Random Forest":
        prediction = rf_model.predict(input_data)[0]
    else:
        prediction = gb_model.predict(input_data)[0]

    st.success(f"Predicted Fuel Efficiency (MPG): {prediction:.2f}")